### ISSUE TITLE
Clarify "disabled" user properties

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-framework-spec#52]
@robertjd and @omgitstom, @bretterer and I were stumbling upon this ambiguity as we were testing laravel this night.

If I post:

`{ "givenName": "Test", "middleName": "Tester", "surname": "McTest", "email": "tester@example.com", "password": "TestTest1"}`

Both express and laravel currently will set the middle name attribute, even though the middle name field is disabled by default in the config. 

```
middleName:
  enabled: false
  label: "Middle Name"
  placeholder: "Middle Name"
  required: true
  type: "text"
```

Does that "disabled" mean that it's not on the form, or that we are not interpreting it as a valid part of the user model?
