### ISSUE TITLE
How should an invalid fieldOrder value be handled?

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-framework-spec#63]
If my configuration for some form route looks like this:

``` yaml
form: 
  fields: 
    login: 
      [...]
    password: 
      [...]
  fieldOrder: 
    - login
    - passwd
```

What should happen when the incorrect/missing value `passwd` is encountered? Should an error be thrown (and when)?
