### ISSUE TITLE
web.verify.nextUri should include status

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-framework-spec#72]
Relevant section of the spec: https://github.com/stormpath/stormpath-framework-spec/blob/master/email-verification.md#get-requests-that-prefer-texthtml

> If the token is valid, redirect to `stormpath.web.verify.nextUri` and append `?status=verified`.

For the `/change` route, we include the status parameter in the [configuration](https://github.com/stormpath/stormpath-framework-spec/blob/master/web-config.yaml#L161), instead of appending it at runtime.

I think `verify.nextUri` should act the same way -- `?status=verified` should be defined in configuration, instead of runtime.

**Comment by omgitstom** [comment]
``` yaml
    verifyEmail:
      enabled: null
      uri: "/verify"
      nextUri: "/login"
      view: "verify"
```

@robertjd @edjiang  - can you update the spec
